#!/bin/bash

WORKDIR=$HOME/go/src/github.com/airdb/.github/bash

source $WORKDIR/alias.sh
source $WORKDIR/export.sh
source $WORKDIR/function.sh

export HOMEBREW_FORCE_BREWED_CURL=1

_myos="$(uname)"
case $_myos in
    Darwin)
        echo 🚦 🚜 🚙 🚘 🚗 🚗 🚕 🚖 🚛 🚌 🚍 🚓 🚔 🚒 🚑 🚐 🚚

        #brew install coreutils
        alias readlink="greadlink"
	export PS1="[\u@\H \W]\$ "
        ;;
    Linux)
	cat $HOME/.config/bar/bug
        ;;
    FreeBSD|OpenBSD)
        echo BSD
        alias foo='/path/to/bsd/bin/foo'
        ;;
    SunOS)
        echo BSD
        alias foo='/path/to/sunos/bin/foo'
        ;;
*) ;;
esac
